# List of applications that need to be installed.
#
# name = the name of the application.
# method = one of ['winget', 'manual'].
# - winget = download and install using winget.
#   - id = the ID of the application in winget.
# - manual = manual download and installation.
#   - url = the download url at which the browser opens.


# Pre-requisites
#   1. Python 3.12+
#   2. Clash & VPN
#   3. Administrator privilege
#   4. Check the latest version


### Language

[[apps]]
name = 'BF'
method = 'winget'
id = 'ChenQingYu.BF' # I contributed

# Include GNU Compiler Collection and NASM
[[apps]]
name = 'Perl'
method = 'winget'
id = 'StrawberryPerl.StrawberryPerl'

[[apps]]
name = 'D'
method = 'winget'
id = 'Dlang.DMD'

[[apps]]
name = 'Erlang'
method = 'winget'
id = 'Erlang.ErlangOTP'

[[apps]]
name = 'Elixir'
method = 'manual'
url = 'https://elixir-lang.org/install.html#windows'

[[apps]]
name = 'Haskell'
method = 'manual'
url = 'https://www.haskell.org/ghcup/'

[[apps]]
name = 'Java'
method = 'winget'
id = 'Oracle.JDK.23' # may need check the latest version

[[apps]]
name = 'JavaScript'
method = 'winget'
id = 'OpenJS.NodeJS.LTS'

[[apps]]
name = 'Lua'
method = 'winget'
id = 'DEVCOM.Lua'

[[apps]]
name = 'Maxima'
method = 'winget'
id = 'MaximaTeam.Maxima'

[[apps]]
name = 'NetLogo'
method = 'winget'
id = 'CCL.NetLogo'

[[apps]]
name = 'Octave'
method = 'winget'
id = 'GNU.Octave'

[[apps]]
name = 'PowerShell'
method = 'winget'
id = 'Microsoft.PowerShell'

[[apps]]
name = 'Prolog'
method = 'winget'
id = 'SWI-Prolog.SWI-Prolog'

[[apps]]
name = 'Racket'
method = 'winget'
id = 'Racket.Racket'

[[apps]]
name = 'Ruby'
method = 'winget'
id = 'RubyInstallerTeam.RubyWithDevKit.3.2' # may need check the latest version

[[apps]]
name = 'Rust'
method = 'winget'
id = 'Rustlang.Rustup'

[[apps]]
name = 'SQL'
method = 'winget'
id = 'SQLite.SQLite'

[[apps]]
name = 'Standard ML'
method = 'winget'
id = 'SMLNJ.SMLNJ.Legacy' # I issued

[[apps]]
name = 'TeX'
method = 'winget'
id = 'MiKTeX.MiKTeX'

[[apps]]
name = 'Typst'
method = 'winget'
id = 'Typst.Typst'

[[apps]]
name = 'Verilog'
method = 'winget'
id = 'Icarus.Verilog' # I issued


### Code

[[apps]]
name = 'Sublime Text'
method = 'winget'
id = 'SublimeHQ.SublimeText.4'

[[apps]]
name = 'MarkText'
method = 'winget'
id = 'MarkText.MarkText'

[[apps]]
name = 'Visual Studio Code'
method = 'winget'
id = 'Microsoft.VisualStudioCode'

[[apps]]
name = 'Visual Studio Community'
method = 'winget'
id = 'Microsoft.VisualStudio.2022.Community' # may need check the latest version

[[apps]]
name = 'Qt'
method = 'manual'
url = 'https://mirror.nju.edu.cn/qt/official_releases/online_installers/qt-unified-windows-x64-online.exe'
# args = '--mirror https://mirror.nju.edu.cn/qt'

[[apps]]
name = 'JetBrains Toolbox'
method = 'winget'
id = 'JetBrains.Toolbox'

[[apps]]
name = 'Unity Hub'
method = 'winget'
id = 'Unity.UnityHub'

[[apps]]
name = 'SQLiteStudio'
method = 'winget'
id = 'PawelSalawa.SQLiteStudio'

[[apps]]
name = 'Git'
method = 'winget'
id = 'Git.Git'

[[apps]]
name = 'Xmake'
method = 'winget'
id = 'Xmake-io.Xmake'

[[apps]]
name = 'Doxygen'
method = 'winget'
id = 'DimitriVanHeesch.Doxygen'

[[apps]]
name = 'Oh My Posh'
method = 'winget'
id = 'JanDeDobbeleer.OhMyPosh'

[[apps]]
name = 'Dr. Memory'
method = 'winget'
id = 'DynamoRIO.drmemory'

[[apps]]
name = 'Zeal'
method = 'winget'
id = 'OlegShparber.Zeal'

[[apps]]
name = 'Inno Setup'
method = 'winget'
id = 'JRSoftware.InnoSetup'

[[apps]]
name = 'Wireshark'
method = 'winget'
id = 'WiresharkFoundation.Wireshark'

[[apps]]
name = 'HxD'
method = 'winget'
id = 'MHNexus.HxD'

[[apps]]
name = 'Graphviz'
method = 'winget'
id = 'Graphviz.Graphviz'

[[apps]]
name = 'Logisim-evolution'
method = 'winget'
id = 'logisim-evolution.logisim-evolution'

[[apps]]
name = 'Sourcetrail'
method = 'winget'
id = 'CoatiSoftware.Sourcetrail' # I issued

[[apps]]
name = 'Windows Package Manager Manifest Creator'
method = 'winget'
id = 'Microsoft.WingetCreate'

[[apps]]
name = 'GitHub CLI'
method = 'winget'
id = 'GitHub.cli'

[[apps]]
name = 'Pandoc'
method = 'winget'
id = 'JohnMacFarlane.Pandoc'

[[apps]]
name = 'Cloc'
method = 'winget'
id = 'AlDanial.Cloc'

[[apps]]
name = 'UMLet'
method = 'manual'
url = 'https://www.umlet.com/changes.htm'

[[apps]]
name = 'x64dbg'
method = 'manual'
url = 'https://x64dbg.com'


### Tool

[[apps]]
name = 'Blender'
method = 'winget'
id = 'BlenderFoundation.Blender'

[[apps]]
name = 'Bandizip'
method = 'winget'
id = 'Bandisoft.Bandizip'

[[apps]]
name = 'Recuva'
method = 'winget'
id = 'Piriform.Recuva'

[[apps]]
name = 'VirtualBox'
method = 'winget'
id = 'Oracle.VirtualBox'

[[apps]]
name = 'Google Earth'
method = 'winget'
id = 'Google.EarthPro'

[[apps]]
name = 'qBittorrent'
method = 'winget'
id = 'qBittorrent.qBittorrent'

[[apps]]
name = 'Free Download Manager'
method = 'winget'
id = 'SoftDeluxe.FreeDownloadManager'

[[apps]]
name = 'WinMerge'
method = 'winget'
id = 'WinMerge.WinMerge'

[[apps]]
name = 'GeoGebra'
method = 'winget'
id = 'GeoGebra.Classic'

[[apps]]
name = 'PotPlayer'
method = 'winget'
id = 'Daum.PotPlayer'

[[apps]]
name = 'Honeyview'
method = 'winget'
id = 'Bandisoft.Honeyview'

[[apps]]
name = 'gnuplot'
method = 'winget'
id = 'gnuplot.gnuplot'

[[apps]]
name = 'Burp Suite'
method = 'winget'
id = 'PortSwigger.BurpSuite.Community'

[[apps]]
name = 'TrafficMonitor'
method = 'winget'
id = 'zhongyang219.TrafficMonitor.Lite'

[[apps]]
name = 'CrystalDiskInfo'
method = 'winget'
id = 'CrystalDewWorld.CrystalDiskInfo.AoiEdition'

[[apps]]
name = 'Fastfetch'
method = 'winget'
id = 'Fastfetch-cli.Fastfetch'

[[apps]]
name = 'Snipaste'
method = 'manual'
url = 'https://www.snipaste.com/download.html'

[[apps]]
name = 'GifCam'
method = 'manual'
url = 'https://blog.bahraniapps.com/gifcam/'

[[apps]]
name = 'EV录屏'
method = 'manual'
url = 'https://www.ieway.cn/evcapture.html'

[[apps]]
name = 'FreePiano'
method = 'manual'
url = 'https://freepiano.tiwb.com/cn/'

[[apps]]
name = 'RustDesk'
method = 'winget'
id = 'RustDesk.RustDesk'

[[apps]]
name = '腾讯会议'
method = 'winget'
id = 'Tencent.TencentMeeting'

[[apps]]
name = '网易云音乐'
method = 'winget'
id = 'NetEase.CloudMusic'

[[apps]]
name = '百度网盘'
method = 'winget'
id = 'Baidu.BaiduNetdisk'


### Social

[[apps]]
name = 'QQ'
method = 'winget'
id = 'Tencent.QQ'

[[apps]]
name = '微信'
method = 'winget'
id = 'Tencent.WeChat'


### Game

[[apps]]
name = 'Golly'
method = 'manual'
url = 'https://sourceforge.net/projects/golly/files/'
